name = "steam-and-sky"
author = "ChefMooon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90e61ea43b768b8212182e8e51f9355be8d9203a63e970426dbdbea97599f5ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"
unsup = "1.2.0"
