name = "steam-and-sky"
author = "ChefMooon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98ce7ee549596c573e4975ecbb5b1103ce9085d14676de6d7d8cc738730993b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"
unsup = "1.2.0"
