name = "steam-and-sky"
author = "ChefMooon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d8f98bc258dbeb12b942b2e1f94c5f8c681bee89bcc3a400784434337458bce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"
unsup = "1.2.0"
